# Generated by Django 4.1 on 2022-10-27 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookkeep',
            old_name='publication',
            new_name='tbook',
        ),
    ]
