# Generated by Django 4.1 on 2022-10-28 10:12

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('BMS', '0002_rename_publication_bookkeep_tbook'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bookkeep',
            managers=[
                ('myObjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='bookkeep',
            name='tbook',
            field=models.CharField(choices=[('Non-Fiction', 'Non-Fiction'), ('Edited', 'Edited'), ('Reference', 'Reference'), ('Fiction', 'Fiction')], max_length=100),
        ),
    ]
