# Generated by Django 4.1 on 2022-11-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMS', '0003_alter_bookkeep_managers_alter_bookkeep_tbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookkeep',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
