# Generated by Django 4.1 on 2022-11-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMS', '0004_bookkeep_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookkeep',
            name='images',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
