# Generated by Django 4.1 on 2022-11-09 04:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BMS', '0006_bookkeep_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookkeep',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
